[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
NODE_VERSION = "18"

[build]
  command = "pnpm run docs:build"
publish = "docs/.vitepress/dist"

[functions]
 node_bundler = "esbuild"

[[redirects]]
  from = "/guide/*"
status = 200
to = "/guide/index.html"
